#!/bin/bash

if [ -z "$1" ]; then
    echo "You must sign the working directory, see -h."
    exit 0
fi

if [ $1 = -h ] || [ $1 = --help ]; then 
        echo
        echo "This script will convert your files using ffmpeg to other filetypes. It will do it in batches, so you can for example convert all your .mp3 to .m4a "
        echo
        echo "Usage; converter /%PATH%/ [original file type] [desired file type] [if wanted, -d to delete the original files]"
        echo "For example: converter /home/Sunde/music/ .webm .mp3 -d"
        echo "Arguments:"
        echo "-h or --help - Show this helpfile."
        echo "-d - The script will delete the original files."
        echo "-v - Show scripts version."
        echo "-f - Show all possible file formats." 
        exit 0
fi

if [ "$1" = -v ] || [ "$1" = --version ]; then 
    echo "Version: 170409-b"
    exit 0
fi
if [ "$1" = -f ]; then
    ffmpeg -formats
    exit 0
fi

if [ -d "$1" ]; then
   for file in "$1"*"$2"; do ffmpeg -i "$file" "$1""$(basename "$file" "$2")"$3""; done
else
    echo "Directory does not exist. Typo?"
    exit 1
fi

if [ "$4" = -d ]; then
     rm "$1"*"$2"
fi
